name: Build import-results

on:
  push:
  pull_request:
  # Rebuild periodically to keep the artefacts fresh
  schedule:
    - cron: "0 1 * * 1"
  workflow_dispatch:

jobs:
  run:
    name: Build iocost-benchmarks-ci
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Checkoutm iocost-benchmarks-ci repository
        uses: actions/checkout@v4
        with:
          path: "iocost-benchmarks-ci"

      - name: Build ci-scripts
        run: cd ${GITHUB_WORKSPACE}/iocost-benchmarks-ci && cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: iocost-benchmarks-ci
          if-no-files-found: error
          path: |
            iocost-benchmarks-ci/target/release/import-results
            iocost-benchmarks-ci/target/release/merge-results
